# Import module

In [4]:
%matplotlib inline               
import pandas as pd              
import numpy as np               
import matplotlib.pyplot as plt  
import tensorflow as tf          

# Import CSV file

In [5]:
dataframe = pd.read_csv("data2.csv")
dataframe = dataframe.drop(["index", "price", "sq_price"], axis=1) 
dataframe = dataframe[0:10] 
dataframe 

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

# Adding column

In [7]:
dataframe.loc[:, ("y1")] = [1, 1, 1, 0, 0, 1, 0, 1, 1, 1] # 1 = like, 0 = bad
dataframe

area  bathrooms  y1
0  2104.0        3.0   1
1  1600.0        3.0   1
2  2400.0        3.0   1
3  1416.0        2.0   0
4  3000.0        4.0   0
5  1985.0        4.0   1
6  1534.0        3.0   0
7  1427.0        3.0   1
8  1380.0        3.0   1
9  1494.0        3.0   1

In [8]:
dataframe.loc[:, ("y2")] = dataframe["y1"] == 0           # y2 is the negation of y1
dataframe

area  bathrooms  y1     y2
0  2104.0        3.0   1  False
1  1600.0        3.0   1  False
2  2400.0        3.0   1  False
3  1416.0        2.0   0   True
4  3000.0        4.0   0   True
5  1985.0        4.0   1  False
6  1534.0        3.0   0   True
7  1427.0        3.0   1  False
8  1380.0        3.0   1  False
9  1494.0        3.0   1  False

In [10]:
dataframe.loc[:, ("y2")] = dataframe["y2"].astype(int)    # Turn TRUE/FALSE values into 1/0
# y2 means we don't like a house
# for Multiclass classification
dataframe 

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

# Transform column to Matrix

In [11]:
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
inputY = dataframe.loc[:, ["y1", "y2"]].as_matrix()

In [12]:
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [13]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

# Parameters

In [14]:
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

# Variables

In [15]:
x = tf.placeholder(tf.float32, [None, 2])   # an array of examples. 
                                            # = array of two float values (area, and number of bathrooms).
                                            # "None" = any number of examples
            
W = tf.Variable(tf.zeros([2, 2]))           # a 2 x 2 float matrix for the weights, make them all zero to begin
b = tf.Variable(tf.zeros([2]))              # 2 bias values

y_values = tf.add(tf.matmul(x, W), b)       # y = mx + b

y = tf.nn.softmax(y_values)                 # activation = softmax
    
y_ = tf.placeholder(tf.float32, [None,2])   # a matrix of labels

# Gradient descent

In [17]:
# Mean squared error
# (1/2m) * (y_ - y)^2 
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initialization

In [20]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# Training 

In [27]:
for i in range(training_epochs):  
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) # Take a gradient descent step using our inputs and labels
    
    # Display weight and bias for 50 progress
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_:inputY})
        print "Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc) #, \"W=", sess.run(W), "b=", sess.run(b)

print "Optimization Finished!"
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print "Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n'

Training step: 0000 cost= 0.109537281
Training step: 0050 cost= 0.109537207
Training step: 0100 cost= 0.109537147
Training step: 0150 cost= 0.109537080
Training step: 0200 cost= 0.109537005
Training step: 0250 cost= 0.109536931
Training step: 0300 cost= 0.109536871
Training step: 0350 cost= 0.109536804
Training step: 0400 cost= 0.109536745
Training step: 0450 cost= 0.109536670
Training step: 0500 cost= 0.109536603
Training step: 0550 cost= 0.109536529
Training step: 0600 cost= 0.109536454
Training step: 0650 cost= 0.109536394
Training step: 0700 cost= 0.109536313
Training step: 0750 cost= 0.109536268
Training step: 0800 cost= 0.109536193
Training step: 0850 cost= 0.109536126
Training step: 0900 cost= 0.109536052
Training step: 0950 cost= 0.109535977
Training step: 1000 cost= 0.109535910
Training step: 1050 cost= 0.109535851
Training step: 1100 cost= 0.109535791
Training step: 1150 cost= 0.109535709
Training step: 1200 cost= 0.109535649
Training step: 1250 cost= 0.109535575
Training ste

# Predict

In [23]:
sess.run(y, feed_dict={x: inputX })

array([[ 0.71125221,  0.28874779],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718789,  0.35281211],
       [ 0.78335613,  0.2166439 ],
       [ 0.70069474,  0.29930523],
       [ 0.65866327,  0.34133676],
       [ 0.64828628,  0.35171372],
       [ 0.64368278,  0.35631716],
       [ 0.65480113,  0.3451989 ]], dtype=float32)

# Result = about 7/10 Right