In [1]:
import numpy as np

# Data collection

In [3]:
x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

In [4]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [5]:
print(y)

[[0]
 [1]
 [1]
 [0]]


# Build model

In [6]:
num_epochs = 60000

# initialize weights
syn0 = 2*np.random.random((3,4))-1
syn1 = 2*np.random.random((4,1))-1

In [19]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [20]:
print(syn0)

[[ 0.4961993  -0.37954756 -0.57554642  0.66956345]
 [-0.65453635 -0.45592747  0.28936107  0.14764008]
 [-0.91283934  0.29540147 -0.30895999  0.23324308]]


In [21]:
print(syn1)

[[-0.47468023]
 [ 0.15621008]
 [-0.43794686]
 [ 0.41325057]]


# Step 3 Train Model

In [26]:
for j in range(num_epochs):
    # feed forward through layers 0, 1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # Optimizing
    l2_error = y-l2
    
    # Print process
    if (j%10000)==0:
        print("Error:"+str(np.mean(np.abs(l2_error))))
    
    # derivative of l2 X l2 Error
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    # Backpropagatoin
    
    # how much did each l1 value contribute
    l1_error = l2_delta.dot(syn1.T)   
    
    # derivative of l1 X l1 Error
    l1_delta = l1_error*nonlin(l1, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.00244655566096
Error:0.00234574340374
Error:0.00225624319405
Error:0.00217609722289
Error:0.00210379022954
Error:0.00203812886084
